import{a as h,i as n,S as g}from"./assets/vendor-Qob_5Ba8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&o(f)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const b="46848522-362871de9bc7c195a5b36e0f9",w="https://pixabay.com/api/";async function p(t,r=1,a=15){const o=`${w}?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{return(await h.get(o)).data}catch{throw new Error("Не вдалося виконати запит")}}function m(t){const r=document.querySelector(".gallery"),a=t.map(o=>`
      <a href="${o.largeImageURL}" class="gallery__item">
        <img src="${o.webformatURL}" alt="${o.tags}" />
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </a>
    `).join("");r.insertAdjacentHTML("beforeend",a)}const L=document.querySelector(".search-form"),y=document.querySelector(".gallery"),l=document.getElementById("load-more");let d="",i=1,c;const u=15;L.addEventListener("submit",async t=>{if(t.preventDefault(),d=t.target.elements.searchQuery.value.trim(),!d){n.warning({title:"Попередження",message:"Будь ласка, введіть запит"});return}i=1,y.innerHTML="",l.style.display="none";try{const r=await p(d,i,u);if(r.hits.length===0){n.error({title:"Помилка",message:"Нічого не знайдено"});return}m(r.hits),l.style.display="block",$(),i*u>=r.totalHits&&(l.style.display="none",n.info({title:"Інформація",message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({title:"Помилка",message:"Не вдалося завантажити зображення"})}});l.addEventListener("click",async()=>{i+=1;try{const t=await p(d,i,u);m(t.hits),c&&c.refresh(),i*u>=t.totalHits&&(l.style.display="none",n.info({title:"Інформація",message:"We're sorry, but you've reached the end of search results."})),v()}catch{n.error({title:"Помилка",message:"Не вдалося завантажити зображення"})}});function $(){c?c.refresh():c=new g(".gallery a")}function v(){const{height:t}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
